-- ============================================================
-- feed_tokens
-- One token per user (unique on user_id).
-- Regenerating = delete old row, insert new row.
-- Token is a random string generated by the application.
-- ============================================================

create table public.feed_tokens (
  id         uuid        primary key default gen_random_uuid(),
  user_id    uuid        not null unique references public.users(id) on delete cascade,
  token      text        not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── RLS ──────────────────────────────────────────────────────
alter table public.feed_tokens enable row level security;

-- Members see only their own token.
create policy "feed_tokens_member_select"
  on public.feed_tokens
  for select
  to authenticated
  using (user_id = auth.uid());

-- Members may create their own token.
create policy "feed_tokens_member_insert"
  on public.feed_tokens
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- Members may delete their own token (for regeneration).
create policy "feed_tokens_member_delete_own"
  on public.feed_tokens
  for delete
  to authenticated
  using (user_id = auth.uid());

-- Admins have full access.
create policy "feed_tokens_admin_all"
  on public.feed_tokens
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());
